#!/usr/bin/env bash
# ~/.git_template.local/hooks/pre-commit
# format-objc-hook
# pre-commit hook to check if any unformatted Objective-C files would be committed. Fails the check if so, and provides instructions.
#
# Copyright 2015 Square, Inc

IFS=$'\n'
export CDPATH=""
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "$DIR"/lib/common-lib.sh

# 保证 .clang-format 文件存在的情况下再执行
[ -e ".clang-format" ] || exit 0

objc_files=$(objc_files_to_format "$1")
[ -z "$objc_files" ] && exit 0

function format_objc() {

  for file in $objc_files; do
    single_success=0
    difference=$("$DIR"/format-objc-file-dry-run.sh "$file" | diff "$file" - | wc -l)
    if [ $difference -gt 0 ]; then
      exit_flag=1
       echo -e "\033[32m>> FileNeedToFormat : '$file' \033[0m\n"
      #后台处理 文件处理 文件对比
       $(cp "$file" "$file.format") 

       if [ -e "$file.format" ]; then
         $("$DIR"/Format-objc-file.sh "$file.format")
        #vimdiff窗体展示
         vimdiff "$file" "$file.format" < /dev/tty > /dev/tty
         
         $(rm -f  "$file.format")
          #窗体关闭后再次校验代码是否进行修改
          double_difference=$("$DIR"/format-objc-file-dry-run.sh "$file" | diff "$file" - | wc -l)
          if [ $double_difference -eq 0 ]; then
            single_success=1
          fi
       fi

      # echo "$single_success"
       # 未成功修改  
      if [ $single_success -eq 0 ]; then
          echo -e "\n\033[31mFormat-One : Format and stage individual files:\033[0m"
          echo -e "\"$DIR\"/Format-objc-file.sh '$file' && git add '$file';\n"
          let success+=1
       # 成功修改 
      elif [ $single_success -eq 1 ]; then
         $(git add "$file")
         # echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      fi

    fi
  done
  if [ $success -eq 1 ]; then
      echo -e "\033[31mFormat-ALL :  Format and stage all affected files:\033[0m\n\"$DIR\"/format-objc-files.sh -s"
      echo -e "\n\033[31mTip-one :\033[0m  There were formatting issues with this commit, run the👆 above👆 command to fix.\n\033[31mTip-two :\033[0m  Commit anyway and skip this check by running git commit --no-verify"
  elif [ $success -eq 0 ] && [ $exit_flag -eq 1 ]; then
      success=0
      echo -e "\033[32m>> success and you need to commit again !!! \033[0m\n"
      #协助提交掉成功的代码
  fi


  return $success 
}
#入口
success=0
exit_flag=0

format_objc 

exit $exit_flag
